### ISSUE TITLE
Crashes When I try to load my mods

### ISSUE THREAD

**Issue by Plasmo322** [Forkk/MultiMC#84]
So MultiMC keeps crashing when I have these mods installed and I have no idea why. Can someone please tell me whats wrong and how I can fix it? I know it works because I played with these exact mods in this launcher a few months ago and now its not working for some reason. I changed nothing.

Crash Log: http://pastebin.com/dKdGKPWn

Mod List: http://pastebin.com/zC1D8iNW

PLEASE GET BACK TO ME ASAP!!!!!!!

**Comment by Jessassin** [comment]
`Caused by: java.lang.ClassNotFoundException: mods.immibis.core.impl.crossmod.EnergyConsumerTraitImpl_BC
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 46 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/power/IPowerReceptor
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 48 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.power.IPowerReceptor
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 52 more`

This appears to be caused by an issue with the mods you are using, not with the launcher.

Further reading, appears to be an issue between immibiscore and buildcraft:

`java.lang.NoClassDefFoundError: mods/immibis/core/impl/crossmod/EnergyConsumerTraitImpl_BC
`
`Caused by: java.lang.NoClassDefFoundError: buildcraft/api/power/IPowerReceptor`
